/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardVisualExplainerRouteImport } from './routes/_authenticated/dashboard.visual-explainer'
import { Route as AuthenticatedDashboardTranslatorRouteImport } from './routes/_authenticated/dashboard.translator'
import { Route as AuthenticatedDashboardSummarizerRouteImport } from './routes/_authenticated/dashboard.summarizer'
import { Route as AuthenticatedDashboardResearchRouteImport } from './routes/_authenticated/dashboard.research'
import { Route as AuthenticatedDashboardQuizRouteImport } from './routes/_authenticated/dashboard.quiz'
import { Route as AuthenticatedDashboardNotesRouteImport } from './routes/_authenticated/dashboard.notes'
import { Route as AuthenticatedDashboardMindmapRouteImport } from './routes/_authenticated/dashboard.mindmap'
import { Route as AuthenticatedDashboardImageGenRouteImport } from './routes/_authenticated/dashboard.image-gen'
import { Route as AuthenticatedDashboardHistoryRouteImport } from './routes/_authenticated/dashboard.history'
import { Route as AuthenticatedDashboardFlashcardsRouteImport } from './routes/_authenticated/dashboard.flashcards'
import { Route as AuthenticatedDashboardCompareRouteImport } from './routes/_authenticated/dashboard.compare'
import { Route as AuthenticatedDashboardCodeTutorRouteImport } from './routes/_authenticated/dashboard.code-tutor'
import { Route as AuthenticatedDashboardChatRouteImport } from './routes/_authenticated/dashboard.chat'
import { Route as AuthenticatedDashboardCalculatorRouteImport } from './routes/_authenticated/dashboard.calculator'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardVisualExplainerRoute =
  AuthenticatedDashboardVisualExplainerRouteImport.update({
    id: '/dashboard/visual-explainer',
    path: '/dashboard/visual-explainer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTranslatorRoute =
  AuthenticatedDashboardTranslatorRouteImport.update({
    id: '/dashboard/translator',
    path: '/dashboard/translator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSummarizerRoute =
  AuthenticatedDashboardSummarizerRouteImport.update({
    id: '/dashboard/summarizer',
    path: '/dashboard/summarizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardResearchRoute =
  AuthenticatedDashboardResearchRouteImport.update({
    id: '/dashboard/research',
    path: '/dashboard/research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardQuizRoute =
  AuthenticatedDashboardQuizRouteImport.update({
    id: '/dashboard/quiz',
    path: '/dashboard/quiz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardNotesRoute =
  AuthenticatedDashboardNotesRouteImport.update({
    id: '/dashboard/notes',
    path: '/dashboard/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMindmapRoute =
  AuthenticatedDashboardMindmapRouteImport.update({
    id: '/dashboard/mindmap',
    path: '/dashboard/mindmap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardImageGenRoute =
  AuthenticatedDashboardImageGenRouteImport.update({
    id: '/dashboard/image-gen',
    path: '/dashboard/image-gen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHistoryRoute =
  AuthenticatedDashboardHistoryRouteImport.update({
    id: '/dashboard/history',
    path: '/dashboard/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardFlashcardsRoute =
  AuthenticatedDashboardFlashcardsRouteImport.update({
    id: '/dashboard/flashcards',
    path: '/dashboard/flashcards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCompareRoute =
  AuthenticatedDashboardCompareRouteImport.update({
    id: '/dashboard/compare',
    path: '/dashboard/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCodeTutorRoute =
  AuthenticatedDashboardCodeTutorRouteImport.update({
    id: '/dashboard/code-tutor',
    path: '/dashboard/code-tutor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardChatRoute =
  AuthenticatedDashboardChatRouteImport.update({
    id: '/dashboard/chat',
    path: '/dashboard/chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCalculatorRoute =
  AuthenticatedDashboardCalculatorRouteImport.update({
    id: '/dashboard/calculator',
    path: '/dashboard/calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/dashboard/code-tutor': typeof AuthenticatedDashboardCodeTutorRoute
  '/dashboard/compare': typeof AuthenticatedDashboardCompareRoute
  '/dashboard/flashcards': typeof AuthenticatedDashboardFlashcardsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/image-gen': typeof AuthenticatedDashboardImageGenRoute
  '/dashboard/mindmap': typeof AuthenticatedDashboardMindmapRoute
  '/dashboard/notes': typeof AuthenticatedDashboardNotesRoute
  '/dashboard/quiz': typeof AuthenticatedDashboardQuizRoute
  '/dashboard/research': typeof AuthenticatedDashboardResearchRoute
  '/dashboard/summarizer': typeof AuthenticatedDashboardSummarizerRoute
  '/dashboard/translator': typeof AuthenticatedDashboardTranslatorRoute
  '/dashboard/visual-explainer': typeof AuthenticatedDashboardVisualExplainerRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/dashboard/code-tutor': typeof AuthenticatedDashboardCodeTutorRoute
  '/dashboard/compare': typeof AuthenticatedDashboardCompareRoute
  '/dashboard/flashcards': typeof AuthenticatedDashboardFlashcardsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/image-gen': typeof AuthenticatedDashboardImageGenRoute
  '/dashboard/mindmap': typeof AuthenticatedDashboardMindmapRoute
  '/dashboard/notes': typeof AuthenticatedDashboardNotesRoute
  '/dashboard/quiz': typeof AuthenticatedDashboardQuizRoute
  '/dashboard/research': typeof AuthenticatedDashboardResearchRoute
  '/dashboard/summarizer': typeof AuthenticatedDashboardSummarizerRoute
  '/dashboard/translator': typeof AuthenticatedDashboardTranslatorRoute
  '/dashboard/visual-explainer': typeof AuthenticatedDashboardVisualExplainerRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/_authenticated/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/_authenticated/dashboard/code-tutor': typeof AuthenticatedDashboardCodeTutorRoute
  '/_authenticated/dashboard/compare': typeof AuthenticatedDashboardCompareRoute
  '/_authenticated/dashboard/flashcards': typeof AuthenticatedDashboardFlashcardsRoute
  '/_authenticated/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/_authenticated/dashboard/image-gen': typeof AuthenticatedDashboardImageGenRoute
  '/_authenticated/dashboard/mindmap': typeof AuthenticatedDashboardMindmapRoute
  '/_authenticated/dashboard/notes': typeof AuthenticatedDashboardNotesRoute
  '/_authenticated/dashboard/quiz': typeof AuthenticatedDashboardQuizRoute
  '/_authenticated/dashboard/research': typeof AuthenticatedDashboardResearchRoute
  '/_authenticated/dashboard/summarizer': typeof AuthenticatedDashboardSummarizerRoute
  '/_authenticated/dashboard/translator': typeof AuthenticatedDashboardTranslatorRoute
  '/_authenticated/dashboard/visual-explainer': typeof AuthenticatedDashboardVisualExplainerRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/calculator'
    | '/dashboard/chat'
    | '/dashboard/code-tutor'
    | '/dashboard/compare'
    | '/dashboard/flashcards'
    | '/dashboard/history'
    | '/dashboard/image-gen'
    | '/dashboard/mindmap'
    | '/dashboard/notes'
    | '/dashboard/quiz'
    | '/dashboard/research'
    | '/dashboard/summarizer'
    | '/dashboard/translator'
    | '/dashboard/visual-explainer'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/calculator'
    | '/dashboard/chat'
    | '/dashboard/code-tutor'
    | '/dashboard/compare'
    | '/dashboard/flashcards'
    | '/dashboard/history'
    | '/dashboard/image-gen'
    | '/dashboard/mindmap'
    | '/dashboard/notes'
    | '/dashboard/quiz'
    | '/dashboard/research'
    | '/dashboard/summarizer'
    | '/dashboard/translator'
    | '/dashboard/visual-explainer'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard/calculator'
    | '/_authenticated/dashboard/chat'
    | '/_authenticated/dashboard/code-tutor'
    | '/_authenticated/dashboard/compare'
    | '/_authenticated/dashboard/flashcards'
    | '/_authenticated/dashboard/history'
    | '/_authenticated/dashboard/image-gen'
    | '/_authenticated/dashboard/mindmap'
    | '/_authenticated/dashboard/notes'
    | '/_authenticated/dashboard/quiz'
    | '/_authenticated/dashboard/research'
    | '/_authenticated/dashboard/summarizer'
    | '/_authenticated/dashboard/translator'
    | '/_authenticated/dashboard/visual-explainer'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/visual-explainer': {
      id: '/_authenticated/dashboard/visual-explainer'
      path: '/dashboard/visual-explainer'
      fullPath: '/dashboard/visual-explainer'
      preLoaderRoute: typeof AuthenticatedDashboardVisualExplainerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/translator': {
      id: '/_authenticated/dashboard/translator'
      path: '/dashboard/translator'
      fullPath: '/dashboard/translator'
      preLoaderRoute: typeof AuthenticatedDashboardTranslatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/summarizer': {
      id: '/_authenticated/dashboard/summarizer'
      path: '/dashboard/summarizer'
      fullPath: '/dashboard/summarizer'
      preLoaderRoute: typeof AuthenticatedDashboardSummarizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/research': {
      id: '/_authenticated/dashboard/research'
      path: '/dashboard/research'
      fullPath: '/dashboard/research'
      preLoaderRoute: typeof AuthenticatedDashboardResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/quiz': {
      id: '/_authenticated/dashboard/quiz'
      path: '/dashboard/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof AuthenticatedDashboardQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/notes': {
      id: '/_authenticated/dashboard/notes'
      path: '/dashboard/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof AuthenticatedDashboardNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/mindmap': {
      id: '/_authenticated/dashboard/mindmap'
      path: '/dashboard/mindmap'
      fullPath: '/dashboard/mindmap'
      preLoaderRoute: typeof AuthenticatedDashboardMindmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/image-gen': {
      id: '/_authenticated/dashboard/image-gen'
      path: '/dashboard/image-gen'
      fullPath: '/dashboard/image-gen'
      preLoaderRoute: typeof AuthenticatedDashboardImageGenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/history': {
      id: '/_authenticated/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/flashcards': {
      id: '/_authenticated/dashboard/flashcards'
      path: '/dashboard/flashcards'
      fullPath: '/dashboard/flashcards'
      preLoaderRoute: typeof AuthenticatedDashboardFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/compare': {
      id: '/_authenticated/dashboard/compare'
      path: '/dashboard/compare'
      fullPath: '/dashboard/compare'
      preLoaderRoute: typeof AuthenticatedDashboardCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/code-tutor': {
      id: '/_authenticated/dashboard/code-tutor'
      path: '/dashboard/code-tutor'
      fullPath: '/dashboard/code-tutor'
      preLoaderRoute: typeof AuthenticatedDashboardCodeTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/chat': {
      id: '/_authenticated/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof AuthenticatedDashboardChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/calculator': {
      id: '/_authenticated/dashboard/calculator'
      path: '/dashboard/calculator'
      fullPath: '/dashboard/calculator'
      preLoaderRoute: typeof AuthenticatedDashboardCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardCalculatorRoute: typeof AuthenticatedDashboardCalculatorRoute
  AuthenticatedDashboardChatRoute: typeof AuthenticatedDashboardChatRoute
  AuthenticatedDashboardCodeTutorRoute: typeof AuthenticatedDashboardCodeTutorRoute
  AuthenticatedDashboardCompareRoute: typeof AuthenticatedDashboardCompareRoute
  AuthenticatedDashboardFlashcardsRoute: typeof AuthenticatedDashboardFlashcardsRoute
  AuthenticatedDashboardHistoryRoute: typeof AuthenticatedDashboardHistoryRoute
  AuthenticatedDashboardImageGenRoute: typeof AuthenticatedDashboardImageGenRoute
  AuthenticatedDashboardMindmapRoute: typeof AuthenticatedDashboardMindmapRoute
  AuthenticatedDashboardNotesRoute: typeof AuthenticatedDashboardNotesRoute
  AuthenticatedDashboardQuizRoute: typeof AuthenticatedDashboardQuizRoute
  AuthenticatedDashboardResearchRoute: typeof AuthenticatedDashboardResearchRoute
  AuthenticatedDashboardSummarizerRoute: typeof AuthenticatedDashboardSummarizerRoute
  AuthenticatedDashboardTranslatorRoute: typeof AuthenticatedDashboardTranslatorRoute
  AuthenticatedDashboardVisualExplainerRoute: typeof AuthenticatedDashboardVisualExplainerRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardCalculatorRoute: AuthenticatedDashboardCalculatorRoute,
  AuthenticatedDashboardChatRoute: AuthenticatedDashboardChatRoute,
  AuthenticatedDashboardCodeTutorRoute: AuthenticatedDashboardCodeTutorRoute,
  AuthenticatedDashboardCompareRoute: AuthenticatedDashboardCompareRoute,
  AuthenticatedDashboardFlashcardsRoute: AuthenticatedDashboardFlashcardsRoute,
  AuthenticatedDashboardHistoryRoute: AuthenticatedDashboardHistoryRoute,
  AuthenticatedDashboardImageGenRoute: AuthenticatedDashboardImageGenRoute,
  AuthenticatedDashboardMindmapRoute: AuthenticatedDashboardMindmapRoute,
  AuthenticatedDashboardNotesRoute: AuthenticatedDashboardNotesRoute,
  AuthenticatedDashboardQuizRoute: AuthenticatedDashboardQuizRoute,
  AuthenticatedDashboardResearchRoute: AuthenticatedDashboardResearchRoute,
  AuthenticatedDashboardSummarizerRoute: AuthenticatedDashboardSummarizerRoute,
  AuthenticatedDashboardTranslatorRoute: AuthenticatedDashboardTranslatorRoute,
  AuthenticatedDashboardVisualExplainerRoute:
    AuthenticatedDashboardVisualExplainerRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
